# You *must* specify "version: 2"
version: 2

requirements:
  signed_off_by:
    required: false

always_pending:
  title_regex: 'WIP'
  labels:
  - wip
    # custom message that will be used for the GitHub status
  explanation: 'Trabalho em progresso...'

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: false
    approve_regex: '^:\+1:'
  reset_on_push:
    enabled: true

# Groups of reviewers and their respective settings
groups:
  desenvolvedores:
    required: 2

    users:
      - alipseight

    conditions:
      branches:
        - master  # this group only reviews when PR is merging into master
      files:
        include:
          - '*.md'
      labels:
        - COMUNIDADE
        - APRIMORAMENTO
        - BACKEND
        - CONTEÚDO
        - CONTRIBUIÇÃO
        - ERRO
        - FRONTEND

    approve_by_comment:
      enabled: true
      approve_regex: '^Approved'  # overrides the default '^:\+1:'
      reject_regex: '^Rejected' 

    author_approval:
      required: true

    reset_on_reopened:
      enabled: true
